### ISSUE TITLE
Cannot sign in using username

### ISSUE THREAD

**Issue by RichardJSun** [Study-Compass/Study-Compass#240]
**Describe the bug**
Cannot sign in using username.

**To Reproduce**
1. Go to home page
2. Click on login
3. Input username and password
4. Fail form validation check on submission

**Expected behavior**
It lets me login 

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 11
 - Browser [e.g. chrome, safari] Brave
 - Version [e.g. 22] Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36

**Additional context**
![image](https://github.com/user-attachments/assets/da678a37-32c0-4505-b984-2cae4763cd5b)

**Comment by AZ0228** [comment]
Thanks for reporting the issue, it's been fixed now
